name: 02_plt

channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
  - phantomjs
  - matplotlib
  - scipy
  - nodejs
  - pip
  - pip:
      - https://github.com/research-licit/vplatoon/archive/v0.2.0.tar.gz
