name: 02_plt

channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab=1.2.3
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
  - phantomjs
  - matplotlib
  - scipy
  - nodejs
  - pip
  - pip:
      - git+https://github.com/research-licit/vplatoon.git@v0.2.0
      - git+https://github.com/research-licit/vplatoon.git@v0.3.0
