name: ITSTools

channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - ipykernel
  - black
  - pytest
  - ipywidgets
  - numpy
  - bokeh
  - pylint
  - pandas
  - ipympl
  - networkx
  - selenium
  - phantomjs
  - matplotlib
  - scipy
  - nodejs
  - pip
  - pip:
      - git+https://github.com/licit-lab/itstools/archive/v0.5.0.tar.gz
